const lang = {
    en: {
        login: 'Log in',
        register: 'Sign up',
        lang: '中文',
        nav_title: 'Multi-currency virtual cards for global payments',
        nav_detail_1: 'VCC Global Card Issuance Business Supports VISA and Mastercard Online Consumption in All Scenarios',
        nav_detail_2: 'VCC Global Card Issuance Business Supports VISA and Mastercard Online Consumption in All Scenarios Global Card Issuance Business is a Visa/Matercard virtual card service launched by VCC in cooperation with international card issuers. Customers can quickly apply for Visa/Matercard virtual cards online and bind them to global multi currency accounts, covering various consumption scenarios. It supports multi currency transactions, is ready to use upon card issuance, real-time receipt, and fast consumption. Greatly enhance the convenience, visibility, and security of your overseas payments.',
        nav_btn_3: 'Starting now',
        data_info_1:'Paid merchant',
        data_info_2:'Transaction amount',
        data_info_3:'Registered users',
        data_info_4:'Circulation',
        card_title: 'Visa and MaserCard two card sets',
        card_content_1: 'pen and use your card instantly',
        card_content_2: 'No 3DS verification, no ADS verification',
        card_content_3: 'Multi-scene support, can be used repeatedly',
        card_content_4: 'Grouped configuration, efficient operation management',
        card_content_5: 'Separate card bin',
        card_content_6: 'Favorable product pricing, convenient product experience',
        card_content_7: 'Multi-scene support for repeated use',
        card_content_8: 'Shared credit model facilitates unified card management for enterprises',
        multi_title: 'Abundant scene supported',
        multi_content_1: 'Cross-border e-commerce platform',
        multi_content_2: 'Amazon, Alibaba, Alilexpress e-commerce platform procurement, pay store rent and other costs',
        multi_content_3: 'Advertising platform',
        multi_content_4: 'Facebook, Google and other overseas marketing promotion costs payment',
        multi_content_5: 'Shipping and logistics costs',
        multi_content_6: 'Shipping platform fees, logistics and storage costs',
        multi_content_7: 'Various tools fees',
        multi_content_8: 'aypal bound consumption, website building system service fee, application market service fee, etc.',
        multi_content_9: 'Payment for studying abroad',
        multi_content_10: 'HKD, USD, GBP multi-currency cards to reduce the exchange loss of tuition paymentHKD, USD, GBP multi-currency cards to reduce the exchange loss of tuition payment',
        advantage_title: 'Product Advantages',
        advantage_content_1: 'Transaction security',
        advantage_content_2: 'International PCI DSS certification',
        advantage_content_3: 'Comprehensive customized risk control configuration',
        advantage_content_4: 'Rich card bin',
        advantage_content_5: 'Multiple card bin to meet the',
        advantage_content_6: 'needs of various transaction scenarios',
        advantage_content_7: 'Efficient card opening',
        advantage_content_8: 'Open cards in seconds, open',
        advantage_content_9: 'multiple cards at once',
        advantage_content_10: 'Multi-currency cards',
        advantage_content_11: 'USD, HKD, GBP currency cards;',
        advantage_content_12: 'meet specific currency payment needs and reduce exchange losses',
        advantage_content_13: 'Multi-scene support',
        advantage_content_14: 'Support multi-scenario and ',
        advantage_content_15: 'multi-platform consumption',
        advantage_content_16: 'Reliable technology',
        advantage_content_17: 'API docking & service platform',
        advantage_content_18: 'card opening',
        advantage_content_19: 'Clear reconciliation',
        advantage_content_20: 'Online multi-card management;',
        advantage_content_21: 'clear online reconciliation of income and expenses',
        advantage_content_22: 'Customer consultation',
        advantage_content_23: 'All-day service on working days ',
        advantage_content_24: 'to ensure customers use the card without worry',
        privacy_title: 'Protecting your privacy and security',
        privacy_content_1: 'Anonymity',
        privacy_content_2: 'Virtual cards provide anonymity, allowing users to obtain cards without providing real identity information, which helps protect personal privacy',
        privacy_content_3: 'Safety',
        privacy_content_4: 'The virtual card generates a new unique card number every time it is opened, reducing the risk of card information being abused',
        privacy_content_5: 'Expenditure control',
        privacy_content_6: 'Users can customize virtual recharge cards as needed, and you can only spend the deposited account funds to limit unnecessary expenses or reduce potential risks',
        privacy_content_7: 'Prevent theft and brushing',
        privacy_content_8: "Due to the fact that virtual cards are not associated with the user's actual credit card account, the risk of credit card information being stolen and swiped is prevented in online shopping",
        privacy_content_9: 'No credit check',
        privacy_content_10: 'Provides a more inclusive way for more people to enjoy the convenience and flexibility of virtual credit cards without being limited by credit checks',
        faq_title: 'Common FAQs',
        faq_content_1: "Provide FAQs to answer users' questions about products, services, purchases, etc",
        faq_content_2: 'What is a virtual credit card?',
        faq_content_3: 'Virtual credit card is a type of credit card without physical cards, and all credit card transactions are conducted through the network. Virtual credit cards generally only have information such as card number, expiration date, and CVV code',
        faq_content_4: 'What payment scenarios can virtual credit cards be used for?',
        faq_content_5: 'Virtual credit cards can be used in payment scenarios such as shopping, online payment and subscription services on the Internet. However, some physical stores may not be able to use virtual credit cards, but some of our card segments support Apple Pay',
        faq_content_6: 'What are the fees for virtual credit cards?',
        faq_content_7: 'Virtual credit cards may charge some fees, such as card opening fees, transaction fees, withdrawal fees, etc. Please register and log in to our system, carefully understand the relevant fee packages on our platform, and choose the suitable package plan for you',
        faq_content_8: 'What is the difference between virtual credit cards and physical credit cards?',
        faq_content_9: 'Virtual credit cards do not have physical cards, only card numbers and other necessary information. Virtual credit cards can be used on the Internet, while physical credit cards need to be used in physical stores or ATMs',
        faq_content_10: 'How to determine the validity period of virtual credit cards?',
        faq_content_11: 'The validity period of virtual credit cards is usually limited, usually several months or one year. Before expiration, you need to reapply or renew your virtual credit card. Our platform provides a quick way to recharge digital currency and fiat currency',
        faq_content_12: 'Can virtual credit cards be used together with physical credit cards?',
        faq_content_13: 'Can be used together. As virtual card accounts are independent of physical card accounts, fund management is more flexible, secure, and convenient. Therefore, you can use different types of cards and methods for payment in different scenarios',
        faq_content_14: 'Is virtual credit card secure?',
        faq_content_15: 'Virtual credit cards generally have higher security because they do not leak card information. In addition, virtual credit cards can be used for one-time transactions, effectively reducing the risk of credit card information being stolen',
        faq_content_16: 'Can virtual credit cards be used for refunds?',
        faq_content_17: 'Virtual credit cards can be used for refunds, and the refunded funds will be returned to your virtual credit card account',
        faq_content_18: 'Can virtual credit cards be rejected?',
        faq_content_19: 'In some cases, virtual credit cards may be rejected. For example, some online merchants may not accept virtual credit cards, or virtual credit cards may not be accepted',
        footer_content_1: 'Official Business',
        footer_content_2: 'Official channel',
        footer_content_3: 'E-mail address',
        nav_home: 'Home',
        nav_service: 'Products',
        nav_advantage: 'Advantages',
        nav_secure: 'Compliance',
        nav_faq: 'FAQ',
        nav_contact: 'Contacts',
    }
}

window.lang = lang